spring:
  application:
    name: eureka-server  
  profiles: peer3

server:
  port: 8763

eureka:
  instance:
    hostname: peer3
    preferIpAddress: false
    ipAddress: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/