spring:
  application:
    name: eureka-server  

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    ipAddress: 192.168.2.111
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.2.120:8761/eureka/,http://192.168.2.123:8761/eureka/

logging:
  config: classpath:logback.xml