spring:
  application:
    name: eureka-server  
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    preferIpAddress: false
    ipAddress: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/